repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    files: ^.*\.(py|md|yml)$
    exclude: >
      (?x)^(
        src/test/fuzzy_test.py|
        src/test/alg_test.py
      )$
    additional_dependencies:
    - tomli
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.10
  hooks:
  - id: ruff-check
    args:
      - --fix
      - --unsafe-fixes
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/pycqa/pylint
  rev: v3.3.8
  hooks:
  - id: pylint
    args:
    - -d import-error
    - -sn
