name: Define Pytest

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  pytest:
    runs-on:
      - ${{ matrix.os }}
      - self-hosted
    strategy:
      matrix:
        os: [Linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install mineflayer
      run: |
        npm install mineflayer
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Save secrets to file
      env:
        USERNAME: ${{ secrets.MCUSERNAME }}
        PASSWORD: ${{ secrets.MCPASSWORD }}
      run: |
        touch password.txt
        echo $USERNAME >> password.txt
        echo $PASSWORD >> password.txt
    - name: Run all tests with pytest
      run: |
        pytest -rs
