name: Define Pylint

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  pylint:
    runs-on:
      - ${{ matrix.os }}
      - self-hosted
    strategy:
      matrix:
        os: [Linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
