name: Run Tests

on: [push,
     pull_request,
     workflow_dispatch]

jobs:
    pylint:
      strategy:
        matrix:
          python-version: ["3.8", "3.12"]
      uses: ./.github/workflows/define-pylint.yml
      with:
        python-version: ${{ matrix.python-version }}
      secrets: inherit
    pytest:
      strategy:
        matrix:
          python-version: ["3.8", "3.12"]
      needs: pylint
      if: github.ref_name == 'master'
      uses: ./.github/workflows/define-pytest.yml
      with:
        python-version: ${{ matrix.python-version }}
      secrets: inherit
