name: Pylint

on: [push]

jobs:
  pylint:
    runs-on:
      - ${{ matrix.os }}
      - self-hosted
    strategy:
      matrix:
        os: [Linux, Windows]
        python-version: ["3.8", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
