name: Run Pylint

on: [push]

jobs:
  pylint:
    strategy:
      matrix:
        python-version: ["3.8", "3.12"]
    uses: ./.github/workflows/define-pylint.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit
