name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install mineflayer
      run: |
        npm install mineflayer
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Save secrets to file
      shell: bash
      env:
        USERNAME: ${{ secrets.MCUSERNAME }}
        PASSWORD: ${{ secrets.MCPASSWORD }}
      run: |
        touch password.txt
        echo $USERNAME >> password.txt
        echo $PASSWORD >> password.txt
    - name: Run all tests with pytest
      run: |
        pytest
